"""Command-line and notebook orchestration for the complete public pipeline."""

from __future__ import annotations

import argparse
from dataclasses import replace
import json
from pathlib import Path
from typing import Any, Mapping, Sequence

import pandas as pd
import yaml

from .artifacts import atomic_write_json, load_json
from .config import PipelineConfig, pipeline_config_from_mapping
from .data import prepare_data
from .diagnostics import (
    compute_loo_knn_diagnostics,
    compute_query_knn_support,
    empirical_pareto_archive,
)
from .evaluator import BWBEvaluator, EvaluationThresholds, make_antithetic_sobol_noise
from .ld_adapter import REQUIRED_LD_FILES, make_ld_adapter
from .manifest import hash_existing_files, hash_mapping, write_run_manifest
from .models import train_or_load_forward, train_or_load_stress_classifier
from .optimization import MultiCaseOptimizationResult, OptimizationConfig, optimize_all_cases
from .reproducibility import SeedRegistry, set_global_determinism
from .schema import (
    ALL_INPUT_COLUMNS,
    ALL_TARGET_COLUMNS,
    CONTINUOUS_DESIGN_COLUMNS,
    DESIGN_COLUMNS,
    FLIGHT_COLUMNS,
    FORWARD_TARGET_COLUMNS,
    STRESS_TARGET_COLUMN,
    TOPOLOGY_COLUMNS,
)
from .topology_budget import build_empirical_topology_prior
from .visualization import (
    plot_empirical_pareto,
    plot_grouped_design_pairplots,
    plot_knn_support_ecdf,
    prepare_pairplot_data,
)


def load_raw_config(path: str | Path) -> dict[str, Any]:
    with Path(path).open("r", encoding="utf-8") as stream:
        values = yaml.safe_load(stream)
    if not isinstance(values, Mapping):
        raise TypeError("The top-level YAML document must be a mapping.")
    return dict(values)


def _resolve(root: Path, path: str | Path) -> Path:
    selected = Path(path)
    return selected if selected.is_absolute() else root / selected


def project_source_files(root: Path) -> list[Path]:
    """Return the executable/public sources whose bytes define a run."""

    candidates = [
        *sorted((root / "src").rglob("*.py")),
        *sorted((root / "scripts").glob("*.py")),
        # The notebook is deterministically generated by build_notebook.py.
        # Hashing its mutable execution outputs would make a harmless Jupyter
        # autosave look like a source-code change.
        root / "pyproject.toml",
        root / "requirements.txt",
        root / "environment.yml",
    ]
    return [path for path in candidates if path.is_file()]


def guard_run_identity(directory: Path, identity: Mapping[str, Any]) -> None:
    directory.mkdir(parents=True, exist_ok=True)
    identity_path = directory / "run_identity.json"
    if identity_path.exists():
        existing = load_json(identity_path)
        if existing != dict(identity):
            raise RuntimeError(
                f"Output directory {directory} belongs to a different "
                "seed/configuration/source tree. Choose a new versioned path."
            )
    else:
        atomic_write_json(identity_path, dict(identity))


def _assert_hash_snapshot(
    paths: Sequence[Path],
    expected: Mapping[str, str],
    *,
    root: Path,
    label: str,
) -> None:
    current = hash_existing_files(paths, base_directory=root)
    if current != dict(expected):
        raise RuntimeError(
            f"{label} changed while the pipeline was running. Results were not "
            "given a misleading final manifest; rerun from a clean process."
        )


def _missions(raw_config: Mapping[str, Any]) -> list[dict[str, Any]]:
    values = raw_config.get("test_cases")
    if not isinstance(values, Sequence) or isinstance(values, (str, bytes)):
        raise TypeError("test_cases must be a sequence of mission mappings.")
    missions = [dict(value) for value in values]
    required = {
        "case_id",
        "condition",
        "LD_target",
        "Payload_target_m3",
        "Fuel_target_m3",
        "Altitude",
        "KCAS",
        "AOA",
    }
    for mission in missions:
        missing = required.difference(mission)
        if missing:
            raise KeyError(f"Mission is missing fields: {sorted(missing)}")
    if len({int(mission["case_id"]) for mission in missions}) != len(missions):
        raise ValueError("case_id values must be unique.")
    return missions


def _save_postprocessing(
    result: MultiCaseOptimizationResult,
    *,
    dataset_rows: pd.DataFrame,
    seed_registry: SeedRegistry,
    output_root: Path,
    k: int,
    maximum_pairplot_rows: int,
) -> dict[str, Any]:
    analysis_root = output_root / "analysis"
    analysis_root.mkdir(parents=True, exist_ok=True)

    loo = compute_loo_knn_diagnostics(dataset_rows, k=k)
    loo.unique_designs.to_csv(
        analysis_root / "dataset_unique_design_loo_knn.csv", index=False
    )
    loo.dataset_rows.to_csv(
        analysis_root / "dataset_rows_with_loo_knn.csv", index=False
    )

    final_designs = result.final_designs.copy()
    training_reference = dataset_rows.loc[dataset_rows["split"] == "train"]
    training_loo = compute_loo_knn_diagnostics(training_reference, k=k)
    training_loo.unique_designs.to_csv(
        analysis_root / "training_unique_design_loo_knn.csv", index=False
    )
    support = compute_query_knn_support(
        training_reference,
        final_designs,
        k=k,
        reference_loo=training_loo.unique_designs,
    )
    support.to_csv(analysis_root / "optimized_design_knn_support.csv", index=False)

    confirmed_tables = []
    accepted_tables = []
    pareto_tables = []
    for case_id in sorted(result.cases):
        case = result.cases[case_id]
        confirmed = case.confirmed_shortlist.copy()
        confirmed["case_id"] = int(case_id)
        confirmed_tables.append(confirmed)
        accepted = confirmed.loc[confirmed["hard_accepted"].astype(bool)].copy()
        accepted_tables.append(accepted)
        pareto = empirical_pareto_archive(confirmed)
        pareto["case_id"] = int(case_id)
        pareto.to_csv(
            analysis_root / f"case_{case_id}_empirical_pareto.csv", index=False
        )
        pareto_tables.append(pareto)
        figure = plot_empirical_pareto(
            pareto,
            selected=case.final_design,
        )
        figure.savefig(
            analysis_root / f"case_{case_id}_empirical_pareto.png",
            dpi=220,
            bbox_inches="tight",
        )
        figure.clf()

    all_confirmed = pd.concat(confirmed_tables, ignore_index=True)
    all_accepted = pd.concat(accepted_tables, ignore_index=True)
    all_pareto = pd.concat(pareto_tables, ignore_index=True)
    all_confirmed.to_csv(analysis_root / "confirmed_candidates_all_cases.csv", index=False)
    all_accepted.to_csv(analysis_root / "accepted_generated_designs.csv", index=False)
    all_pareto.to_csv(
        analysis_root / "empirical_pareto_all_cases.csv", index=False
    )

    pairplot_data = prepare_pairplot_data(
        dataset_rows,
        all_accepted,
        selected=final_designs,
        maximum_dataset_rows=maximum_pairplot_rows,
        sample_seed=seed_registry.derive("plots/pairplot_sample"),
    )
    pairplot_data.dataset_scatter.to_csv(
        analysis_root / "pairplot_dataset_sample.csv", index=False
    )
    figures = plot_grouped_design_pairplots(pairplot_data)
    for name, figure in figures.items():
        figure.savefig(
            analysis_root / f"design_pairplot_{name}.png",
            dpi=180,
            bbox_inches="tight",
        )
        figure.clf()

    figure = plot_knn_support_ecdf(training_loo.unique_designs, support)
    figure.savefig(
        analysis_root / "knn_distance_ecdf.png", dpi=220, bbox_inches="tight"
    )
    figure.clf()
    return {
        "unique_dataset_designs": int(len(loo.unique_designs)),
        "confirmed_candidates": int(len(all_confirmed)),
        "accepted_generated_candidates": int(len(all_accepted)),
        "empirical_pareto_rows": int(len(all_pareto)),
        "selected_designs": int(len(final_designs)),
    }


def run_pipeline(
    config_path: str | Path,
    *,
    project_root: str | Path = ".",
    master_seed: int | None = None,
    force_retrain: bool = False,
    models_only: bool = False,
) -> dict[str, Any]:
    """Run the full deterministic pipeline and return the final summary."""

    root = Path(project_root).resolve()
    config_path = _resolve(root, config_path).resolve()
    raw = load_raw_config(config_path)
    if master_seed is not None:
        raw["master_seed"] = int(master_seed)
    typed: PipelineConfig = pipeline_config_from_mapping(raw)
    if force_retrain:
        typed = replace(
            typed,
            forward_model=replace(typed.forward_model, force_retrain=True),
            stress_classifier=replace(
                typed.stress_classifier, force_retrain=True
            ),
        )

    source_files = project_source_files(root)
    source_hashes = hash_existing_files(source_files, base_directory=root)
    data_path = _resolve(root, typed.project.data_path)
    ld_source_files: list[Path] = []
    critical_input_files = [config_path, data_path, *source_files]
    if not models_only:
        ld_source_root = _resolve(root, typed.project.ld_model_dir)
        ld_source_files = [ld_source_root / name for name in REQUIRED_LD_FILES]
        critical_input_files.extend(ld_source_files)
    critical_input_snapshot = hash_existing_files(
        critical_input_files, base_directory=root
    )
    output_root = _resolve(root, typed.project.output_root)
    run_identity = {
        "schema": "bwb-run-identity-v2",
        "master_seed": typed.master_seed,
        "config_sha256": hash_mapping(raw),
        "source_tree_sha256": hash_mapping(source_hashes),
    }
    guard_run_identity(output_root, run_identity)
    seed_registry = SeedRegistry(typed.master_seed)
    determinism = set_global_determinism(
        seed_registry.derive("pipeline/global", upper_bound=2**32),
        strict=typed.determinism.strict,
        torch_num_threads=typed.determinism.torch_num_threads,
    )

    split_manifest_path = output_root / typed.data.split_manifest
    bundle = prepare_data(
        data_path,
        typed.data,
        seed_registry,
        split_manifest_path=split_manifest_path,
    )

    optimization_values = raw.get("optimization")
    if not isinstance(optimization_values, Mapping):
        raise TypeError("optimization must be a mapping.")
    if float(optimization_values["nominal_probability_threshold"]) != float(
        typed.stress_classifier.probability_threshold
    ):
        raise ValueError(
            "Stress-report and optimization nominal thresholds must be identical."
        )
    if float(optimization_values["robust_probability_threshold"]) != float(
        typed.stress_classifier.noise_median_probability_threshold
    ):
        raise ValueError(
            "Stress-report and optimization robustness thresholds must be identical."
        )
    missions = _missions(raw)
    topology_prior = None
    optimization_root = None
    if not models_only:
        # Fail before expensive model training if the user-requested support
        # rule produces no eligible topology.
        topology_prior = build_empirical_topology_prior(
            bundle.rows,
            missions,
            stress_limit_mpa=typed.stress_classifier.stress_limit_mpa,
            minimum_feasible_unique_designs=int(
                optimization_values["minimum_feasible_unique_designs_per_topology"]
            ),
            split=optimization_values.get("topology_prior_split", "train"),
            eligibility_split=optimization_values.get(
                "topology_eligibility_split", None
            ),
        )
        topology_prior.to_csv(
            output_root / "topology_empirical_prior.csv", index=False
        )
        optimization_root = _resolve(
            root,
            optimization_values.get("output_dir", "final_optimization_results"),
        )
        guard_run_identity(optimization_root, run_identity)
    forward_dir = _resolve(root, typed.forward_model.output_dir)
    stress_dir = _resolve(root, typed.stress_classifier.output_dir)
    forward = train_or_load_forward(
        bundle,
        typed.forward_model,
        seed_registry,
        artifact_dir=forward_dir,
        device=typed.determinism.device,
    )
    stress = train_or_load_stress_classifier(
        bundle,
        typed.stress_classifier,
        seed_registry,
        artifact_dir=stress_dir,
    )
    if tuple(forward.feature_names) != tuple(DESIGN_COLUMNS):
        raise AssertionError("Forward artifact violated the exact 21-input contract.")
    if tuple(stress.feature_names) != tuple(ALL_INPUT_COLUMNS):
        raise AssertionError("Stress artifact violated the exact 24-input contract.")

    stages: dict[str, Any] = {
        "determinism": determinism,
        "data": {
            "rows": int(len(bundle.rows)),
            "unique_designs": int(len(bundle.structural_designs)),
            "dataset_fingerprint": bundle.dataset_fingerprint,
            "split_fingerprint": bundle.split_manifest.split_fingerprint,
            "exact_duplicates_removed": bundle.exact_duplicate_rows_removed,
            "conflicting_stress_input_groups": len(
                bundle.conflicting_stress_input_groups
            ),
        },
        "models": {
            "forward_artifact_id": forward.artifact_id,
            "stress_artifact_id": stress.artifact_id,
        },
    }
    schema = {
        "design_columns": DESIGN_COLUMNS,
        "continuous_design_columns": CONTINUOUS_DESIGN_COLUMNS,
        "topology_columns": TOPOLOGY_COLUMNS,
        "flight_columns": FLIGHT_COLUMNS,
        "forward_targets": FORWARD_TARGET_COLUMNS,
        "stress_target": STRESS_TARGET_COLUMN,
        "all_targets": ALL_TARGET_COLUMNS,
    }
    execution = {
        "mode": "models_only" if models_only else "full",
        "force_retrain": bool(force_retrain),
        "models_only": bool(models_only),
        "source_tree_sha256": run_identity["source_tree_sha256"],
    }
    base_input_files = [config_path, bundle.source_path, *source_files]
    model_directories = (forward_dir, stress_dir)

    def current_model_files() -> list[Path]:
        return [
            path
            for directory in model_directories
            for path in directory.rglob("*")
            if path.is_file()
        ]

    model_files = current_model_files()
    model_snapshot = hash_existing_files(model_files, base_directory=root)
    if models_only:
        _assert_hash_snapshot(
            [config_path, data_path, *project_source_files(root)],
            critical_input_snapshot,
            root=root,
            label="Source/config/data inputs",
        )
        _assert_hash_snapshot(
            current_model_files(),
            model_snapshot,
            root=root,
            label="Model artifacts",
        )
        summary = {
            "status": "models_ready",
            "output_root": str(output_root),
            **stages,
        }
        (output_root / "models_only_summary.json").write_text(
            json.dumps(summary, indent=2, sort_keys=True, allow_nan=False) + "\n",
            encoding="utf-8",
        )
        output_files = [
            path
            for directory in (output_root, forward_dir, stress_dir)
            for path in directory.rglob("*")
            if path.is_file() and path.name != "run_manifest.json"
        ]
        manifest = write_run_manifest(
            output_root / "run_manifest.json",
            project_root=root,
            config=raw,
            seed_manifest=seed_registry.manifest(),
            schema=schema,
            input_files=base_input_files,
            output_files=output_files,
            stages=stages,
            execution=execution,
        )
        summary["manifest_sha256"] = manifest["manifest_file_sha256"]
        return summary

    models_only_summary = output_root / "models_only_summary.json"
    if models_only_summary.exists():
        models_only_summary.unlink()
    search_n = int(optimization_values["search_noise_samples"])
    confirmation_n = int(optimization_values["confirmation_noise_samples"])
    search_bank = make_antithetic_sobol_noise(
        search_n,
        len(CONTINUOUS_DESIGN_COLUMNS),
        seed_registry.derive("probability_noise/search"),
    )
    confirmation_bank = make_antithetic_sobol_noise(
        confirmation_n,
        len(CONTINUOUS_DESIGN_COLUMNS),
        seed_registry.derive("probability_noise/confirmation"),
    )
    ld_values = raw.get("ld_model", {})
    if not isinstance(ld_values, Mapping):
        raise TypeError("ld_model must be a mapping.")
    if ld_values.get("reject_any_warning") is not True:
        raise ValueError("Published optimization requires reject_any_warning=true.")
    if ld_values.get("require_finite_ld_cl_cd") is not True:
        raise ValueError(
            "Published optimization requires require_finite_ld_cl_cd=true."
        )
    _assert_hash_snapshot(
        [config_path, data_path, *project_source_files(root), *ld_source_files],
        critical_input_snapshot,
        root=root,
        label="Source/config/data/LD inputs before L/D loading",
    )
    ld_adapter = make_ld_adapter(
        _resolve(root, typed.project.ld_model_dir),
        cache=True,
        max_cache_entries=int(ld_values.get("cache_max_entries", 50_000)),
    )
    evaluator = BWBEvaluator(
        forward,
        stress,
        ld_adapter,
        search_noise_bank=search_bank,
        confirmation_noise_bank=confirmation_bank,
        noise_fractions=tuple(
            float(value)
            for value in optimization_values["noise_fractions_of_bound_width"]
        ),
        thresholds=EvaluationThresholds(
            nominal_probability=float(
                optimization_values["nominal_probability_threshold"]
            ),
            robust_probability=float(
                optimization_values["robust_probability_threshold"]
            ),
        ),
    )
    if topology_prior is None:
        raise AssertionError("Full execution requires a preflight topology prior.")
    optimization_config = OptimizationConfig.from_mapping(optimization_values)
    if optimization_root is None:
        raise AssertionError("Full execution requires an optimization output root.")
    optimization_result = optimize_all_cases(
        evaluator,
        missions,
        topology_prior,
        optimization_config,
        seed_registry,
        checkpoint_directory=optimization_root,
    )
    optimization_result.save(optimization_root)
    stages["optimization"] = {
        "cases": sorted(optimization_result.cases),
        "rounds": len(optimization_config.rounds),
        "repeats": optimization_config.repeats,
        "search_noise_samples": search_n,
        "confirmation_noise_samples": confirmation_n,
        "search_noise_bank_sha256": __import__("hashlib").sha256(
            search_bank.astype("<f8").tobytes()
        ).hexdigest(),
        "confirmation_noise_bank_sha256": __import__("hashlib").sha256(
            confirmation_bank.astype("<f8").tobytes()
        ).hexdigest(),
    }

    analysis_values = raw.get("analysis", {})
    stages["analysis"] = _save_postprocessing(
        optimization_result,
        dataset_rows=bundle.rows,
        seed_registry=seed_registry,
        output_root=output_root,
        k=int(analysis_values.get("knn_k", 5)),
        maximum_pairplot_rows=int(
            analysis_values.get("pairplot_max_dataset_rows", 3000)
        ),
    )

    model_files = current_model_files()
    input_files = list(base_input_files)
    ld_root = _resolve(root, typed.project.ld_model_dir)
    input_files.extend(ld_root / name for name in REQUIRED_LD_FILES)
    input_files.extend(model_files)
    _assert_hash_snapshot(
        [
            config_path,
            data_path,
            *project_source_files(root),
            *ld_source_files,
        ],
        critical_input_snapshot,
        root=root,
        label="Source/config/data/LD inputs",
    )
    _assert_hash_snapshot(
        model_files,
        model_snapshot,
        root=root,
        label="Model artifacts",
    )
    output_files = [
        path
        for directory in (output_root, optimization_root, forward_dir, stress_dir)
        for path in directory.rglob("*")
        if path.is_file() and path.name != "run_manifest.json"
    ]
    manifest = write_run_manifest(
        output_root / "run_manifest.json",
        project_root=root,
        config=raw,
        seed_manifest=seed_registry.manifest(),
        schema=schema,
        input_files=input_files,
        output_files=output_files,
        stages=stages,
        execution=execution,
    )
    return {
        "status": "completed",
        "output_root": str(output_root),
        "optimization_root": str(optimization_root),
        "final_designs": optimization_result.final_designs,
        "manifest_sha256": manifest["manifest_file_sha256"],
        "stages": stages,
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", default="configs/default.yaml")
    parser.add_argument("--project-root", default=".")
    parser.add_argument("--master-seed", type=int, default=None)
    parser.add_argument("--force-retrain", action="store_true")
    parser.add_argument("--models-only", action="store_true")
    arguments = parser.parse_args(argv)
    result = run_pipeline(
        arguments.config,
        project_root=arguments.project_root,
        master_seed=arguments.master_seed,
        force_retrain=arguments.force_retrain,
        models_only=arguments.models_only,
    )
    print(f"Pipeline status: {result['status']}")
    print(f"Output root: {result['output_root']}")
    if "final_designs" in result:
        print(result["final_designs"].to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
